//Generated by fm_generateAeroSurfacePoints.py from fm.p3d. Re-running resets every value.

    class Wings {
        class Wing01 {
            name           = "leftWing";
            facing         = "up";
            numElements    = 2;
            airfoil        = "NACA 4418";
            chordLinePos   = 0.25;
            panels[] =
            {
              {{-2.450, 2.072,-0.278},{-1.470, 2.299, 0.049},{-1.470, 1.152,-0.031},{-2.450, 1.174,-0.341}}
             ,{{-1.470, 2.299, 0.049},{-0.600, 2.449, 0.059},{-0.600, 1.152,-0.031},{-1.470, 1.152,-0.031}}
            };
        };
        class Wing02 {
            name           = "rightWing";
            facing         = "up";
            numElements    = 2;
            airfoil        = "NACA 4418";
            chordLinePos   = 0.25;
            panels[] =
            {
              {{ 0.600, 2.449, 0.059},{ 1.470, 2.299, 0.049},{ 1.470, 1.152,-0.031},{ 0.600, 1.152,-0.031}}
             ,{{ 1.470, 2.299, 0.049},{ 2.450, 2.072,-0.278},{ 2.450, 1.174,-0.341},{ 1.470, 1.152,-0.031}}
            };
        };
        class Wing03 {
            name           = "horizontalStabilizer";
            facing         = "up";
            numElements    = 4;
            airfoil        = "NACA 0012";
            chordLinePos   = 0.25;
            panels[] =
            {
              {{-1.575,-5.761,-0.365},{ 1.724,-5.761,-0.365},{ 1.584,-6.558,-0.435},{-1.715,-6.558,-0.435}}
            };
        };
        class Wing04 {
            name           = "verticalFin";
            facing         = "right";
            numElements    = 4;
            airfoil        = "NACA 4418";
            chordLinePos   = 0.25;
            panels[] =
            {
              {{ 0.000,-6.863, 1.700},{ 0.000,-4.900,-0.068},{ 0.000,-6.250,-0.240},{ 0.000,-7.636, 1.700}}
            };
        };
        class Wing05 {
            name           = "leftVerticalFin";
            facing         = "right";
            numElements    = 1;
            airfoil        = "NACA 0012";
            chordLinePos   = 0.25;
            panels[] =
            {
              {{ 1.567,-6.653, 0.520},{ 1.737,-5.688,-0.340},{ 1.579,-6.585,-0.340},{ 1.449,-7.323, 0.520}}
             ,{{ 1.737,-5.693,-0.340},{ 1.716,-5.812,-0.720},{ 1.636,-6.265,-0.720},{ 1.579,-6.591,-0.340}}
            };
        };
        class Wing06 {
            name           = "rightVerticalFin";
            facing         = "right";
            numElements    = 1;
            airfoil        = "NACA 0012";
            chordLinePos   = 0.25;
            panels[] =
            {
              {{-1.733,-6.653, 0.520},{-1.563,-5.688,-0.340},{-1.721,-6.585,-0.340},{-1.851,-7.323, 0.520}}
             ,{{-1.563,-5.693,-0.340},{-1.584,-5.812,-0.720},{-1.664,-6.265,-0.720},{-1.721,-6.591,-0.340}}
            };
        };
    };
